### ISSUE TITLE
Some bugs

### ISSUE THREAD

**Issue by wasdspace** [Hellish-Mods/Amber#3]
They're not really technically Amber's bugs, but these mods no longer maintain their 1.16 version or lack of Jade supports, so one can only hope that Amber hacks them.

IF has incorrect mod name display:
![2023-07-12_21 04 38](https://github.com/Hellish-Mods/Amber/assets/85009668/218fcf1a-d603-4ab9-8444-5c7f6e990403)

AE2's ME Controller has wrong energy display:
![2023-07-12_21 05 05](https://github.com/Hellish-Mods/Amber/assets/85009668/f5e1661b-1724-4057-afe6-153b7a9e9847)

IE's multiblocks have double FE display(need to point to energy input/output):
![2023-07-12_21 09 02](https://github.com/Hellish-Mods/Amber/assets/85009668/7cd5e354-39ad-4dd8-ba3e-709f91dbd6de)

**Comment by Gcat101** [comment]
The last 2 are known amber bugs that I'm trying to fix. The 1st one is a jade bug, I'll try to fix it as well.

**Comment by wasdspace** [comment]
The second one seems to be an AE2's bug, as TOP display it's always 0 too.
Sorry I really should have installed the TOP at the first time for comparison.

**Comment by Gcat101** [comment]
![2023-07-12_17 04 21](https://github.com/Hellish-Mods/Amber/assets/79367505/890f5c57-9881-476c-8d00-85c53bdfe016)

**Comment by Gcat101** [comment]
me controller fixed

**Comment by Gcat101** [comment]
probably also fixes IE multiblocks, didn't check yet though

**Comment by wasdspace** [comment]
That's great!
By the way, is it possible to make Amber not show non-existent block textures, like modern Jade?
(Oops did I just say "modern"...)
Wait a minite I'll send a picture.

**Comment by wasdspace** [comment]
![2023-07-12_22 21 02](https://github.com/Hellish-Mods/Amber/assets/85009668/0ce7886f-e6c9-4523-80c4-f4abf1d42567)

**Comment by Gcat101** [comment]
I'll try to add support for this, might also include like a blacklist for blocks and entities like in 1.18+ jade

**Comment by Snownee** [comment]
The first one is not Jade's bug. Use the search function on GitHub

**Comment by Gcat101** [comment]
From what I can tell it is, because if you use the mod tooltip mod instead it does show the correct tooltip like JEI does. I had the same thing happen when I was playing with the original version of Jade.

**Comment by Gcat101** [comment]
1 fixed

![image](https://github.com/Hellish-Mods/Amber/assets/79367505/5b4d49de-f20c-46f6-8b21-6b5b725258b8)

**Comment by Gcat101** [comment]
> That's great! By the way, is it possible to make Amber not show non-existent block textures, like modern Jade? (Oops did I just say "modern"...) Wait a minite I'll send a picture.

After a bit of digging, I found out that this is not a jade feature, but instead it's ars using a different model for light blocks in 1.18+. Can't do anything about it

**Comment by Gcat101** [comment]
I think all of the bugs you've mentioned here have been addressed, so I'm closing this. If you find any others, open a new issue
