### ISSUE TITLE
Crash when looking at a dynamic trees fruit, mentions this mod

### ISSUE THREAD

**Issue by Enterprise12nx01** [Hellish-Mods/Amber#5]
When looking at a fruit from dynamic trees it causes a client crash mentioning waila

https://gist.github.com/Enterprise12nx01/afc86b05805b39e1158be17c1ad91a6a

**Comment by Gcat101** [comment]
Does this happen with regular Jade?

**Comment by Gcat101** [comment]
Hmm, can't seem to reproduce. What version of Amber are you using?

![2023-08-08_14 53 44](https://github.com/Hellish-Mods/Amber/assets/79367505/c65361fe-279c-4d88-acbf-4e808713003b)

**Comment by Gcat101** [comment]
Any more insight? @Enterprise12nx01

**Comment by Enterprise12nx01** [comment]
> Any more insight? @Enterprise12nx01

Hi apologies, been busy. I will try to rest tomorrow and find another tree. They seem rare to find and I don't remember it well as I was just exploring and went to look at the fruit, I will get back if I reproduce the issue

**Comment by unnecessarymb** [comment]
I have additional insight on this issue.

User Ekofy on MPD reported this problem:

"I’m working on a custom modpack and I’ve run into a unique error. 
Playing on my server, whenever I look at a fruit (from Pam’s harvestcraft dynamic trees compat mod) my game crashes.
 Looking at my crash logs, it is waila that is causing the crash when it tries to load info about the fruit. 

Here’s the weird part though - the issue doesn’t happen on single player, and loading into single player, finding a fruit to look at, then loading back into the server fixes the issue temporarily.

…what?"

Later they said they have tried Waila, Jade, and Amber.

**Comment by Ekofy** [comment]
It's me, the guy mentioned in the above comment. here is my crash report
[https://mclo.gs/Oug86p6](https://mclo.gs/Oug86p6)

**Comment by Gcat101** [comment]
Unfortunately, afaik it's not on my side, so I'll close this as not planned rn. I'll reopen it if I manage to find more info on how to fix this.

**Comment by Enterprise12nx01** [comment]
Happened again in a fresh world, looking at a papaya, only happens with Jade or Amber(tested both)
[crash-2024-01-05_21.45.47-client.txt](https://github.com/Hellish-Mods/Amber/files/13848133/crash-2024-01-05_21.45.47-client.txt)

@supermassimo @Harleyoc1 @Snownee

**Comment by Gcat101** [comment]
Yep, not our side
